In [2]:
#Importing numpy as its alias
import numpy as np

In [5]:
#Creating a numpy array
np_array = np.array([1,2,3,4])
np_array
type(np_array)

numpy.ndarray

In [9]:
#Multiplying every number in a array by 2

#In python
numbers = [1,2,3,4,5]
doubled = []

for num in numbers:
    doubled.append(num * 2)
print(doubled)

[2, 4, 6, 8, 10]


In [13]:
#multiplying a numpy array by 2

np_array = np.array([doubled])
np_doubled = np_array * 2
np_doubled



array([[ 4,  8, 12, 16, 20]])

In [18]:
#Creating arrays in different ways
#Creating an array of 5  zeros 
np_zeros = np.zeros(5)
np_zeros
#Creating an array of 5 ones
np_ones = np.ones(5)
np_ones
#an array of numbers from 0 to 9
np_arrange = np.arange(0,10)
np_arrange

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
#Creating an array of random numbers

#Creating an array of 500 random numbers
np_random = np.random.random(500)
np_random

array([4.16661521e-01, 2.16842197e-01, 7.99149345e-01, 9.37230612e-01,
       6.85980732e-01, 7.11818637e-01, 9.71007304e-01, 1.28093322e-01,
       7.84675257e-01, 1.45905739e-02, 2.18264900e-01, 7.92988533e-01,
       7.13360009e-01, 6.95282935e-01, 4.58538239e-01, 5.81867658e-02,
       2.94945143e-01, 1.41236761e-01, 2.00566211e-01, 6.96243788e-02,
       1.78333235e-01, 6.28420963e-01, 2.42619888e-01, 4.51239409e-01,
       3.26160579e-01, 8.90866781e-01, 6.42944710e-02, 1.18151226e-01,
       1.50721446e-01, 9.46441328e-01, 5.26247568e-01, 5.51579297e-01,
       9.36215677e-01, 7.95028928e-01, 6.67042988e-01, 6.48806105e-01,
       4.70477219e-01, 9.43156581e-02, 9.74385816e-01, 2.65051923e-01,
       1.34593313e-01, 5.33016066e-01, 1.40766202e-01, 2.14995367e-01,
       9.86111184e-01, 2.50806457e-01, 9.36326071e-01, 4.77356766e-01,
       4.74666534e-01, 3.25588004e-01, 8.91970664e-01, 7.89703389e-01,
       3.06106038e-01, 5.60869797e-01, 7.29999698e-01, 6.10805585e-01,
      

In [20]:
#creating an array of 500 random integers from 1 to 100

np_randint = np.random.randint(0,100,500)
np_randint

array([41, 71, 31, 41, 56,  7, 50, 74, 87, 20, 95, 65, 58, 77, 36, 29, 41,
       13, 94, 15,  7, 73, 35,  2, 65, 91,  9, 44, 35,  9, 77, 88, 77, 15,
       79, 14, 34, 43, 49, 59, 22,  8, 47, 20, 80, 80, 22, 65, 15, 56,  7,
       25, 95, 55, 19, 82, 94, 26,  8, 31, 57, 32, 23, 94,  0, 23, 74,  1,
       56, 27,  2, 92, 17, 53, 27, 89, 68, 92, 88, 72, 90, 43, 59, 15, 71,
        7, 76, 33, 24, 41, 43, 79, 25, 27, 69, 44, 30, 51, 18, 71, 51, 44,
        1,  4, 17, 69, 36, 89, 47, 30,  9, 13, 88, 69,  2, 41, 30, 61,  7,
       94,  7,  2, 73, 19, 57, 14, 52, 89, 91,  4, 34, 41, 45, 63,  9, 77,
       45, 25, 36, 63, 62,  9, 29,  2, 95, 77, 15, 86, 46, 18, 73, 47, 13,
        2, 52, 48, 65,  8, 46, 21, 52, 96, 86, 29, 45, 82, 93, 84, 15, 85,
        1, 74, 90, 94, 53, 90, 13, 38, 11, 60, 70, 66, 47, 39,  1, 89, 70,
       65, 94,  3, 61, 52, 68,  0, 78, 65,  9, 43, 12, 89, 13, 65, 73, 40,
       89, 26,  5, 86, 24, 56, 56, 59,  5, 35, 60, 75, 26, 25, 37, 94, 73,
       75, 30, 64, 58, 50

In [22]:
#finding out the shape, size, and dimension

np_randint.shape
np_arrange.shape


(10,)

In [23]:
#Indexing (Getting specific elements)

n_array = np_randint
np_randint[2]

np.int32(31)

In [24]:
#Creating a 2d numpy array 

n_arr = np.array([[1,2,3,4,5], [6,7,8,9,0]])
n_arr 

array([[1, 2, 3, 4, 5],
       [6, 7, 8, 9, 0]])

In [ ]:
#vector opratins in python